In [5]:
#1
import numpy as np
tup = (1.1, 2.2, 3.3, 4.4, 5.5)
lis = [1.1, 2.2, 3.3, 4.4, 5.5]
arrt = np.array(tup, dtype=float)
arrl = np.array(lis, dtype=float)
print(arrt)
print(arrl)

[1.1 2.2 3.3 4.4 5.5]
[1.1 2.2 3.3 4.4 5.5]


In [4]:
#2
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
slic = arr[2:7]
ind = arr[[2, 3, 5]]
boo = arr % 2 == 0
booo = arr[boo]
print(booo)
print(ind)
print(slic)

[0 2 4 6 8]
[2 3 5]
[2 3 4 5 6]


In [3]:
#3
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
min = np.min(arr)
max = np.max(arr)
suum = np.sum(arr)
cum = np.cumsum(arr)
print(min)
print(max)
print(suum)
print(cum)


0
8
36
[ 0  1  3  6 10 15 21 28 36]


In [6]:
#4
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
dimm = arr.ndim
shap = arr.shape
siz = arr.size
typ = arr.dtype
print(dimm)
print(shap)
print(siz)
print(typ)


2
(3, 3)
9
int32


In [9]:
#5
import pandas as pd
data = {'A': 10, 'B': 20, 'C': 30, 'D': 40}
mydata = pd.Series(data)
print(mydata['A'])
print(mydata[0])


10
10


C:\Users\Joanna letica Pinto\AppData\Local\Temp\ipykernel_14052\68864417.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(mydata[0])


In [10]:
#6
arr = np.array([1, 2, 3, 4, 5, 6])
minn = np.min(arr)
maxx = np.max(arr)
cumm = np.cumsum(arr)
summ = np.sum(arr)
print(cumm)
print(summ)
print(maxx)
print(minn)


[ 1  3  6 10 15 21]
21
6
1


In [11]:
#7
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank = np.linalg.matrix_rank(matrix)
deter = np.linalg.det(matrix)
trace = np.trace(matrix)
eigen = np.linalg.eigvals(matrix)
print(matrix)
print(rank)
print(deter)
print(trace)
print(eigen)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
0.0
15
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]


In [12]:
#8
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
X = np.array([9, 0])
Y = np.array([11, 12])
dot = np.dot(X, Y)
outer = np.outer(X, Y)
inner = np.inner(A, B)
prod = np.matmul(A, B)
exponent = 2
matex = np.linalg.matrix_power(A, exponent)
linearmatrix = np.linalg.solve(A, X)
print(dot)
print(outer)
print(inner)
print(prod)
print(matex)
print(linearmatrix)


99
[[ 99 108]
 [  0   0]]
[[17 23]
 [39 53]]
[[19 22]
 [43 50]]
[[ 7 10]
 [15 22]]
[-18.   13.5]
